### ISSUE TITLE
Objednavka sa po zaplateni vymaze

### ISSUE THREAD

**Issue by TheMartes** [24pay/24payopencart#1]
Akonahle sa platba uhradi ze platobnu branu, objednavka sa vymaze so systemu, hoci nadalej ostava ulozena v databaze. Neodosle sa email v podstate ako keby sa zrusila. Error logy ostavaju prazdne a API endopointy nehlasia ziadne chyby

**Comment by 24pay** [comment]
Aktualny update by mal tento problem vyriesit. Problem bol v zle nastavenej NURL. Tym padom ostali objednavky s order_status_id = 0. A taketo objednavky sa v zozname nezobrazuju.
